services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 16686:16686
      - 4317:4317
      - 4318:4318
    networks:
      kong-net:
  swagger:
    image: swaggerapi/swagger-ui
    restart: always
    environment:
      - SWAGGER_JSON=/openapi.json
    volumes:
      - ./openapi/api.swagger.swagger.json:/openapi.json
    ports:
      - 5000:8080
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-ppassword",
        ]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s
    networks:
      kong-net:
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql-data:/var/lib/mysql # 将 MySQL 数据挂载到命名卷
    ports:
      - 3307:3306
  consul:
    image: hashicorp/consul
    restart: always
    ports:
      - 8500:8500
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8500/v1/status/leader"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s
    networks:
      kong-net:
  user:
    build:
      context: .
      dockerfile: ./app/user/service/Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
        restart: true
      consul:
        condition: service_healthy
    # ports:
    #   - 8000:8000
    #   - 9000:9000
    networks:
      kong-net:
  authn:
    build:
      context: .
      dockerfile: ./app/authn/service/Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
        restart: true
      consul:
        condition: service_healthy
    # ports:
    #   - 8001:8000
    #   - 9001:9000
    networks:
      kong-net:
  order:
    build:
      context: .
      dockerfile: ./app/order/service/Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
        restart: true
      consul:
        condition: service_healthy
    # ports:
    #   - 8002:8000
    #   - 9002:9000
    networks:
      kong-net:
  commission:
    build:
      context: .
      dockerfile: ./app/commission/service/Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
        restart: true
      consul:
        condition: service_healthy
    # ports:
    #   - 8003:8000
    #   - 9003:9000
    networks:
      kong-net:
  stats:
    build:
      context: .
      dockerfile: ./app/stats/service/Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
        restart: true
      consul:
        condition: service_healthy
    networks:
      kong-net:
networks:
  kong-net:
    driver: bridge
    external: true
volumes:
  mysql-data:
