// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.0--dev
// source: order/service/v1/order.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListOrderByUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrderByUserRequest) Reset() {
	*x = ListOrderByUserRequest{}
	mi := &file_order_service_v1_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrderByUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrderByUserRequest) ProtoMessage() {}

func (x *ListOrderByUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_v1_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrderByUserRequest.ProtoReflect.Descriptor instead.
func (*ListOrderByUserRequest) Descriptor() ([]byte, []int) {
	return file_order_service_v1_order_proto_rawDescGZIP(), []int{0}
}

func (x *ListOrderByUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListOrderByDomainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrderByDomainRequest) Reset() {
	*x = ListOrderByDomainRequest{}
	mi := &file_order_service_v1_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrderByDomainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrderByDomainRequest) ProtoMessage() {}

func (x *ListOrderByDomainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_v1_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrderByDomainRequest.ProtoReflect.Descriptor instead.
func (*ListOrderByDomainRequest) Descriptor() ([]byte, []int) {
	return file_order_service_v1_order_proto_rawDescGZIP(), []int{1}
}

func (x *ListOrderByDomainRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type CreateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PaymentType   string                 `protobuf:"bytes,2,opt,name=payment_type,json=paymentType,proto3" json:"payment_type,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Amount        int32                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"` // rmb 分
	Domain        string                 `protobuf:"bytes,5,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_order_service_v1_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_v1_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_service_v1_order_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOrderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateOrderRequest) GetPaymentType() string {
	if x != nil {
		return x.PaymentType
	}
	return ""
}

func (x *CreateOrderRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateOrderRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateOrderRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type CreateOrderReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PaymentType   string                 `protobuf:"bytes,2,opt,name=payment_type,json=paymentType,proto3" json:"payment_type,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Amount        int32                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"` // rmb 分
	Domain        string                 `protobuf:"bytes,5,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderReply) Reset() {
	*x = CreateOrderReply{}
	mi := &file_order_service_v1_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderReply) ProtoMessage() {}

func (x *CreateOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_v1_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderReply.ProtoReflect.Descriptor instead.
func (*CreateOrderReply) Descriptor() ([]byte, []int) {
	return file_order_service_v1_order_proto_rawDescGZIP(), []int{3}
}

func (x *CreateOrderReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateOrderReply) GetPaymentType() string {
	if x != nil {
		return x.PaymentType
	}
	return ""
}

func (x *CreateOrderReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateOrderReply) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateOrderReply) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_order_service_v1_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_v1_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_service_v1_order_proto_rawDescGZIP(), []int{4}
}

func (x *GetOrderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetOrderReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PaymentType   string                 `protobuf:"bytes,2,opt,name=payment_type,json=paymentType,proto3" json:"payment_type,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Amount        int32                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"` // rmb 分
	Domain        string                 `protobuf:"bytes,5,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderReply) Reset() {
	*x = GetOrderReply{}
	mi := &file_order_service_v1_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderReply) ProtoMessage() {}

func (x *GetOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_v1_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderReply.ProtoReflect.Descriptor instead.
func (*GetOrderReply) Descriptor() ([]byte, []int) {
	return file_order_service_v1_order_proto_rawDescGZIP(), []int{5}
}

func (x *GetOrderReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetOrderReply) GetPaymentType() string {
	if x != nil {
		return x.PaymentType
	}
	return ""
}

func (x *GetOrderReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetOrderReply) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *GetOrderReply) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type ListOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrderRequest) Reset() {
	*x = ListOrderRequest{}
	mi := &file_order_service_v1_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrderRequest) ProtoMessage() {}

func (x *ListOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_v1_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrderRequest.ProtoReflect.Descriptor instead.
func (*ListOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_service_v1_order_proto_rawDescGZIP(), []int{6}
}

type ListOrderReply struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Orders        []*ListOrderReply_Order `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrderReply) Reset() {
	*x = ListOrderReply{}
	mi := &file_order_service_v1_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrderReply) ProtoMessage() {}

func (x *ListOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_v1_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrderReply.ProtoReflect.Descriptor instead.
func (*ListOrderReply) Descriptor() ([]byte, []int) {
	return file_order_service_v1_order_proto_rawDescGZIP(), []int{7}
}

func (x *ListOrderReply) GetOrders() []*ListOrderReply_Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

type ListOrderReply_Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PaymentType   string                 `protobuf:"bytes,2,opt,name=payment_type,json=paymentType,proto3" json:"payment_type,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Amount        int32                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"` // rmb 分
	Domain        string                 `protobuf:"bytes,5,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrderReply_Order) Reset() {
	*x = ListOrderReply_Order{}
	mi := &file_order_service_v1_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrderReply_Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrderReply_Order) ProtoMessage() {}

func (x *ListOrderReply_Order) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_v1_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrderReply_Order.ProtoReflect.Descriptor instead.
func (*ListOrderReply_Order) Descriptor() ([]byte, []int) {
	return file_order_service_v1_order_proto_rawDescGZIP(), []int{7, 0}
}

func (x *ListOrderReply_Order) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ListOrderReply_Order) GetPaymentType() string {
	if x != nil {
		return x.PaymentType
	}
	return ""
}

func (x *ListOrderReply_Order) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListOrderReply_Order) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ListOrderReply_Order) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

var File_order_service_v1_order_proto protoreflect.FileDescriptor

const file_order_service_v1_order_proto_rawDesc = "" +
	"\n" +
	"\x1corder/service/v1/order.proto\x12\x14api.order.service.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\":\n" +
	"\x16ListOrderByUserRequest\x12 \n" +
	"\auser_id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x06userId\";\n" +
	"\x18ListOrderByDomainRequest\x12\x1f\n" +
	"\x06domain\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x06domain\"\xb8\x01\n" +
	"\x12CreateOrderRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x02id\x12*\n" +
	"\fpayment_type\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\vpaymentType\x12\x1b\n" +
	"\x04name\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04name\x12\x1f\n" +
	"\x06amount\x18\x04 \x01(\x05B\a\xfaB\x04\x1a\x02 \x00R\x06amount\x12\x1f\n" +
	"\x06domain\x18\x05 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x06domain\"\x89\x01\n" +
	"\x10CreateOrderReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fpayment_type\x18\x02 \x01(\tR\vpaymentType\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x05R\x06amount\x12\x16\n" +
	"\x06domain\x18\x05 \x01(\tR\x06domain\"*\n" +
	"\x0fGetOrderRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x02id\"\x86\x01\n" +
	"\rGetOrderReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fpayment_type\x18\x02 \x01(\tR\vpaymentType\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x05R\x06amount\x12\x16\n" +
	"\x06domain\x18\x05 \x01(\tR\x06domain\"\x12\n" +
	"\x10ListOrderRequest\"\xd4\x01\n" +
	"\x0eListOrderReply\x12B\n" +
	"\x06orders\x18\x01 \x03(\v2*.api.order.service.v1.ListOrderReply.OrderR\x06orders\x1a~\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fpayment_type\x18\x02 \x01(\tR\vpaymentType\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x05R\x06amount\x12\x16\n" +
	"\x06domain\x18\x05 \x01(\tR\x06domain2\xfc\x04\n" +
	"\x05Order\x12v\n" +
	"\vCreateOrder\x12(.api.order.service.v1.CreateOrderRequest\x1a&.api.order.service.v1.CreateOrderReply\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/orders\x12o\n" +
	"\bGetOrder\x12%.api.order.service.v1.GetOrderRequest\x1a#.api.order.service.v1.GetOrderReply\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/orders/{id}\x12m\n" +
	"\tListOrder\x12&.api.order.service.v1.ListOrderRequest\x1a$.api.order.service.v1.ListOrderReply\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/orders\x12\x89\x01\n" +
	"\x0fListOrderByUser\x12,.api.order.service.v1.ListOrderByUserRequest\x1a$.api.order.service.v1.ListOrderReply\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/v1/users/{user_id}/orders\x12\x8e\x01\n" +
	"\x11ListOrderByDomain\x12..api.order.service.v1.ListOrderByDomainRequest\x1a$.api.order.service.v1.ListOrderReply\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/v1/domains/{domain}/ordersB8\n" +
	"\x14api.order.service.v1P\x01Z\x1eagents/api/order/service/v1;v1b\x06proto3"

var (
	file_order_service_v1_order_proto_rawDescOnce sync.Once
	file_order_service_v1_order_proto_rawDescData []byte
)

func file_order_service_v1_order_proto_rawDescGZIP() []byte {
	file_order_service_v1_order_proto_rawDescOnce.Do(func() {
		file_order_service_v1_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_service_v1_order_proto_rawDesc), len(file_order_service_v1_order_proto_rawDesc)))
	})
	return file_order_service_v1_order_proto_rawDescData
}

var file_order_service_v1_order_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_order_service_v1_order_proto_goTypes = []any{
	(*ListOrderByUserRequest)(nil),   // 0: api.order.service.v1.ListOrderByUserRequest
	(*ListOrderByDomainRequest)(nil), // 1: api.order.service.v1.ListOrderByDomainRequest
	(*CreateOrderRequest)(nil),       // 2: api.order.service.v1.CreateOrderRequest
	(*CreateOrderReply)(nil),         // 3: api.order.service.v1.CreateOrderReply
	(*GetOrderRequest)(nil),          // 4: api.order.service.v1.GetOrderRequest
	(*GetOrderReply)(nil),            // 5: api.order.service.v1.GetOrderReply
	(*ListOrderRequest)(nil),         // 6: api.order.service.v1.ListOrderRequest
	(*ListOrderReply)(nil),           // 7: api.order.service.v1.ListOrderReply
	(*ListOrderReply_Order)(nil),     // 8: api.order.service.v1.ListOrderReply.Order
}
var file_order_service_v1_order_proto_depIdxs = []int32{
	8, // 0: api.order.service.v1.ListOrderReply.orders:type_name -> api.order.service.v1.ListOrderReply.Order
	2, // 1: api.order.service.v1.Order.CreateOrder:input_type -> api.order.service.v1.CreateOrderRequest
	4, // 2: api.order.service.v1.Order.GetOrder:input_type -> api.order.service.v1.GetOrderRequest
	6, // 3: api.order.service.v1.Order.ListOrder:input_type -> api.order.service.v1.ListOrderRequest
	0, // 4: api.order.service.v1.Order.ListOrderByUser:input_type -> api.order.service.v1.ListOrderByUserRequest
	1, // 5: api.order.service.v1.Order.ListOrderByDomain:input_type -> api.order.service.v1.ListOrderByDomainRequest
	3, // 6: api.order.service.v1.Order.CreateOrder:output_type -> api.order.service.v1.CreateOrderReply
	5, // 7: api.order.service.v1.Order.GetOrder:output_type -> api.order.service.v1.GetOrderReply
	7, // 8: api.order.service.v1.Order.ListOrder:output_type -> api.order.service.v1.ListOrderReply
	7, // 9: api.order.service.v1.Order.ListOrderByUser:output_type -> api.order.service.v1.ListOrderReply
	7, // 10: api.order.service.v1.Order.ListOrderByDomain:output_type -> api.order.service.v1.ListOrderReply
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_order_service_v1_order_proto_init() }
func file_order_service_v1_order_proto_init() {
	if File_order_service_v1_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_service_v1_order_proto_rawDesc), len(file_order_service_v1_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_service_v1_order_proto_goTypes,
		DependencyIndexes: file_order_service_v1_order_proto_depIdxs,
		MessageInfos:      file_order_service_v1_order_proto_msgTypes,
	}.Build()
	File_order_service_v1_order_proto = out.File
	file_order_service_v1_order_proto_goTypes = nil
	file_order_service_v1_order_proto_depIdxs = nil
}
