CREATE TABLE IF NOT EXISTS orders (
    id VARCHAR(30) UNIQUE PRIMARY KEY,
    payment_type VARCHAR(10) NOT NULL,
    name VARCHAR(255) NOT NULL,
    amount INT NOT NULL,
    domain VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);