// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.0--dev
// source: api/stats/service/v1/stats.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterEvent) Reset() {
	*x = RegisterEvent{}
	mi := &file_api_stats_service_v1_stats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterEvent) ProtoMessage() {}

func (x *RegisterEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_stats_service_v1_stats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterEvent.ProtoReflect.Descriptor instead.
func (*RegisterEvent) Descriptor() ([]byte, []int) {
	return file_api_stats_service_v1_stats_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterEvent) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *RegisterEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RechargeEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Product       string                 `protobuf:"bytes,4,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RechargeEvent) Reset() {
	*x = RechargeEvent{}
	mi := &file_api_stats_service_v1_stats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RechargeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RechargeEvent) ProtoMessage() {}

func (x *RechargeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_stats_service_v1_stats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RechargeEvent.ProtoReflect.Descriptor instead.
func (*RechargeEvent) Descriptor() ([]byte, []int) {
	return file_api_stats_service_v1_stats_proto_rawDescGZIP(), []int{1}
}

func (x *RechargeEvent) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *RechargeEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RechargeEvent) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *RechargeEvent) GetProduct() string {
	if x != nil {
		return x.Product
	}
	return ""
}

type CreateEventReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Types that are valid to be assigned to Data:
	//
	//	*CreateEventReq_Register
	//	*CreateEventReq_Recharge
	Data          isCreateEventReq_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventReq) Reset() {
	*x = CreateEventReq{}
	mi := &file_api_stats_service_v1_stats_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventReq) ProtoMessage() {}

func (x *CreateEventReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_stats_service_v1_stats_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventReq.ProtoReflect.Descriptor instead.
func (*CreateEventReq) Descriptor() ([]byte, []int) {
	return file_api_stats_service_v1_stats_proto_rawDescGZIP(), []int{2}
}

func (x *CreateEventReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateEventReq) GetData() isCreateEventReq_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CreateEventReq) GetRegister() *RegisterEvent {
	if x != nil {
		if x, ok := x.Data.(*CreateEventReq_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *CreateEventReq) GetRecharge() *RechargeEvent {
	if x != nil {
		if x, ok := x.Data.(*CreateEventReq_Recharge); ok {
			return x.Recharge
		}
	}
	return nil
}

type isCreateEventReq_Data interface {
	isCreateEventReq_Data()
}

type CreateEventReq_Register struct {
	Register *RegisterEvent `protobuf:"bytes,10,opt,name=register,proto3,oneof"`
}

type CreateEventReq_Recharge struct {
	Recharge *RechargeEvent `protobuf:"bytes,11,opt,name=recharge,proto3,oneof"`
}

func (*CreateEventReq_Register) isCreateEventReq_Data() {}

func (*CreateEventReq_Recharge) isCreateEventReq_Data() {}

type CreateEventReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventReply) Reset() {
	*x = CreateEventReply{}
	mi := &file_api_stats_service_v1_stats_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventReply) ProtoMessage() {}

func (x *CreateEventReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_stats_service_v1_stats_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventReply.ProtoReflect.Descriptor instead.
func (*CreateEventReply) Descriptor() ([]byte, []int) {
	return file_api_stats_service_v1_stats_proto_rawDescGZIP(), []int{3}
}

var File_api_stats_service_v1_stats_proto protoreflect.FileDescriptor

const file_api_stats_service_v1_stats_proto_rawDesc = "" +
	"\n" +
	" api/stats/service/v1/stats.proto\x12\x14api.stats.service.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"R\n" +
	"\rRegisterEvent\x12\x1f\n" +
	"\x06domain\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x06domain\x12 \n" +
	"\auser_id\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x06userId\"\x96\x01\n" +
	"\rRechargeEvent\x12\x1f\n" +
	"\x06domain\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x06domain\x12 \n" +
	"\auser_id\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x06userId\x12\x1f\n" +
	"\x06amount\x18\x03 \x01(\x03B\a\xfaB\x04\"\x02 \x01R\x06amount\x12!\n" +
	"\aproduct\x18\x04 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\aproduct\"\xbb\x01\n" +
	"\x0eCreateEventReq\x12\x1b\n" +
	"\x04type\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04type\x12A\n" +
	"\bregister\x18\n" +
	" \x01(\v2#.api.stats.service.v1.RegisterEventH\x00R\bregister\x12A\n" +
	"\brecharge\x18\v \x01(\v2#.api.stats.service.v1.RechargeEventH\x00R\brechargeB\x06\n" +
	"\x04data\"\x12\n" +
	"\x10CreateEventReply2\x81\x01\n" +
	"\x05Stats\x12x\n" +
	"\vCreateEvent\x12$.api.stats.service.v1.CreateEventReq\x1a&.api.stats.service.v1.CreateEventReply\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/stats/eventsB8\n" +
	"\x14api.stats.service.v1P\x01Z\x1eagents/api/stats/service/v1;v1b\x06proto3"

var (
	file_api_stats_service_v1_stats_proto_rawDescOnce sync.Once
	file_api_stats_service_v1_stats_proto_rawDescData []byte
)

func file_api_stats_service_v1_stats_proto_rawDescGZIP() []byte {
	file_api_stats_service_v1_stats_proto_rawDescOnce.Do(func() {
		file_api_stats_service_v1_stats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_stats_service_v1_stats_proto_rawDesc), len(file_api_stats_service_v1_stats_proto_rawDesc)))
	})
	return file_api_stats_service_v1_stats_proto_rawDescData
}

var file_api_stats_service_v1_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_stats_service_v1_stats_proto_goTypes = []any{
	(*RegisterEvent)(nil),    // 0: api.stats.service.v1.RegisterEvent
	(*RechargeEvent)(nil),    // 1: api.stats.service.v1.RechargeEvent
	(*CreateEventReq)(nil),   // 2: api.stats.service.v1.CreateEventReq
	(*CreateEventReply)(nil), // 3: api.stats.service.v1.CreateEventReply
}
var file_api_stats_service_v1_stats_proto_depIdxs = []int32{
	0, // 0: api.stats.service.v1.CreateEventReq.register:type_name -> api.stats.service.v1.RegisterEvent
	1, // 1: api.stats.service.v1.CreateEventReq.recharge:type_name -> api.stats.service.v1.RechargeEvent
	2, // 2: api.stats.service.v1.Stats.CreateEvent:input_type -> api.stats.service.v1.CreateEventReq
	3, // 3: api.stats.service.v1.Stats.CreateEvent:output_type -> api.stats.service.v1.CreateEventReply
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_stats_service_v1_stats_proto_init() }
func file_api_stats_service_v1_stats_proto_init() {
	if File_api_stats_service_v1_stats_proto != nil {
		return
	}
	file_api_stats_service_v1_stats_proto_msgTypes[2].OneofWrappers = []any{
		(*CreateEventReq_Register)(nil),
		(*CreateEventReq_Recharge)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_stats_service_v1_stats_proto_rawDesc), len(file_api_stats_service_v1_stats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_stats_service_v1_stats_proto_goTypes,
		DependencyIndexes: file_api_stats_service_v1_stats_proto_depIdxs,
		MessageInfos:      file_api_stats_service_v1_stats_proto_msgTypes,
	}.Build()
	File_api_stats_service_v1_stats_proto = out.File
	file_api_stats_service_v1_stats_proto_goTypes = nil
	file_api_stats_service_v1_stats_proto_depIdxs = nil
}
