// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.0--dev
// source: api/commission/service/v1/wallet.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	WalletType    string                 `protobuf:"bytes,2,opt,name=wallet_type,json=walletType,proto3" json:"wallet_type,omitempty"`
	Account       *string                `protobuf:"bytes,3,opt,name=account,proto3,oneof" json:"account,omitempty"`
	QrCode        *string                `protobuf:"bytes,4,opt,name=qr_code,json=qrCode,proto3,oneof" json:"qr_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWalletRequest) Reset() {
	*x = CreateWalletRequest{}
	mi := &file_api_commission_service_v1_wallet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWalletRequest) ProtoMessage() {}

func (x *CreateWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_commission_service_v1_wallet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWalletRequest.ProtoReflect.Descriptor instead.
func (*CreateWalletRequest) Descriptor() ([]byte, []int) {
	return file_api_commission_service_v1_wallet_proto_rawDescGZIP(), []int{0}
}

func (x *CreateWalletRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateWalletRequest) GetWalletType() string {
	if x != nil {
		return x.WalletType
	}
	return ""
}

func (x *CreateWalletRequest) GetAccount() string {
	if x != nil && x.Account != nil {
		return *x.Account
	}
	return ""
}

func (x *CreateWalletRequest) GetQrCode() string {
	if x != nil && x.QrCode != nil {
		return *x.QrCode
	}
	return ""
}

type CreateWalletReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	WalletType    string                 `protobuf:"bytes,2,opt,name=wallet_type,json=walletType,proto3" json:"wallet_type,omitempty"`
	Account       *string                `protobuf:"bytes,3,opt,name=account,proto3,oneof" json:"account,omitempty"`
	QrCode        *string                `protobuf:"bytes,4,opt,name=qr_code,json=qrCode,proto3,oneof" json:"qr_code,omitempty"`
	Id            string                 `protobuf:"bytes,5,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWalletReply) Reset() {
	*x = CreateWalletReply{}
	mi := &file_api_commission_service_v1_wallet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWalletReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWalletReply) ProtoMessage() {}

func (x *CreateWalletReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_commission_service_v1_wallet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWalletReply.ProtoReflect.Descriptor instead.
func (*CreateWalletReply) Descriptor() ([]byte, []int) {
	return file_api_commission_service_v1_wallet_proto_rawDescGZIP(), []int{1}
}

func (x *CreateWalletReply) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateWalletReply) GetWalletType() string {
	if x != nil {
		return x.WalletType
	}
	return ""
}

func (x *CreateWalletReply) GetAccount() string {
	if x != nil && x.Account != nil {
		return *x.Account
	}
	return ""
}

func (x *CreateWalletReply) GetQrCode() string {
	if x != nil && x.QrCode != nil {
		return *x.QrCode
	}
	return ""
}

func (x *CreateWalletReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateWalletReply) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type UpdateWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Account       *string                `protobuf:"bytes,3,opt,name=account,proto3,oneof" json:"account,omitempty"`
	QrCode        *string                `protobuf:"bytes,4,opt,name=qr_code,json=qrCode,proto3,oneof" json:"qr_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWalletRequest) Reset() {
	*x = UpdateWalletRequest{}
	mi := &file_api_commission_service_v1_wallet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWalletRequest) ProtoMessage() {}

func (x *UpdateWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_commission_service_v1_wallet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWalletRequest.ProtoReflect.Descriptor instead.
func (*UpdateWalletRequest) Descriptor() ([]byte, []int) {
	return file_api_commission_service_v1_wallet_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateWalletRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateWalletRequest) GetAccount() string {
	if x != nil && x.Account != nil {
		return *x.Account
	}
	return ""
}

func (x *UpdateWalletRequest) GetQrCode() string {
	if x != nil && x.QrCode != nil {
		return *x.QrCode
	}
	return ""
}

type UpdateWalletReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	WalletType    string                 `protobuf:"bytes,2,opt,name=wallet_type,json=walletType,proto3" json:"wallet_type,omitempty"`
	Account       *string                `protobuf:"bytes,3,opt,name=account,proto3,oneof" json:"account,omitempty"`
	QrCode        *string                `protobuf:"bytes,4,opt,name=qr_code,json=qrCode,proto3,oneof" json:"qr_code,omitempty"`
	Id            string                 `protobuf:"bytes,5,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWalletReply) Reset() {
	*x = UpdateWalletReply{}
	mi := &file_api_commission_service_v1_wallet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWalletReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWalletReply) ProtoMessage() {}

func (x *UpdateWalletReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_commission_service_v1_wallet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWalletReply.ProtoReflect.Descriptor instead.
func (*UpdateWalletReply) Descriptor() ([]byte, []int) {
	return file_api_commission_service_v1_wallet_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateWalletReply) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateWalletReply) GetWalletType() string {
	if x != nil {
		return x.WalletType
	}
	return ""
}

func (x *UpdateWalletReply) GetAccount() string {
	if x != nil && x.Account != nil {
		return *x.Account
	}
	return ""
}

func (x *UpdateWalletReply) GetQrCode() string {
	if x != nil && x.QrCode != nil {
		return *x.QrCode
	}
	return ""
}

func (x *UpdateWalletReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateWalletReply) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type DeleteWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWalletRequest) Reset() {
	*x = DeleteWalletRequest{}
	mi := &file_api_commission_service_v1_wallet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWalletRequest) ProtoMessage() {}

func (x *DeleteWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_commission_service_v1_wallet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWalletRequest.ProtoReflect.Descriptor instead.
func (*DeleteWalletRequest) Descriptor() ([]byte, []int) {
	return file_api_commission_service_v1_wallet_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteWalletRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteWalletReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWalletReply) Reset() {
	*x = DeleteWalletReply{}
	mi := &file_api_commission_service_v1_wallet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWalletReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWalletReply) ProtoMessage() {}

func (x *DeleteWalletReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_commission_service_v1_wallet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWalletReply.ProtoReflect.Descriptor instead.
func (*DeleteWalletReply) Descriptor() ([]byte, []int) {
	return file_api_commission_service_v1_wallet_proto_rawDescGZIP(), []int{5}
}

type GetWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletRequest) Reset() {
	*x = GetWalletRequest{}
	mi := &file_api_commission_service_v1_wallet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletRequest) ProtoMessage() {}

func (x *GetWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_commission_service_v1_wallet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletRequest.ProtoReflect.Descriptor instead.
func (*GetWalletRequest) Descriptor() ([]byte, []int) {
	return file_api_commission_service_v1_wallet_proto_rawDescGZIP(), []int{6}
}

func (x *GetWalletRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetWalletReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	WalletType    string                 `protobuf:"bytes,2,opt,name=wallet_type,json=walletType,proto3" json:"wallet_type,omitempty"`
	Account       *string                `protobuf:"bytes,3,opt,name=account,proto3,oneof" json:"account,omitempty"`
	QrCode        *string                `protobuf:"bytes,4,opt,name=qr_code,json=qrCode,proto3,oneof" json:"qr_code,omitempty"`
	Id            string                 `protobuf:"bytes,5,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletReply) Reset() {
	*x = GetWalletReply{}
	mi := &file_api_commission_service_v1_wallet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletReply) ProtoMessage() {}

func (x *GetWalletReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_commission_service_v1_wallet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletReply.ProtoReflect.Descriptor instead.
func (*GetWalletReply) Descriptor() ([]byte, []int) {
	return file_api_commission_service_v1_wallet_proto_rawDescGZIP(), []int{7}
}

func (x *GetWalletReply) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetWalletReply) GetWalletType() string {
	if x != nil {
		return x.WalletType
	}
	return ""
}

func (x *GetWalletReply) GetAccount() string {
	if x != nil && x.Account != nil {
		return *x.Account
	}
	return ""
}

func (x *GetWalletReply) GetQrCode() string {
	if x != nil && x.QrCode != nil {
		return *x.QrCode
	}
	return ""
}

func (x *GetWalletReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetWalletReply) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ListWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWalletRequest) Reset() {
	*x = ListWalletRequest{}
	mi := &file_api_commission_service_v1_wallet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWalletRequest) ProtoMessage() {}

func (x *ListWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_commission_service_v1_wallet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWalletRequest.ProtoReflect.Descriptor instead.
func (*ListWalletRequest) Descriptor() ([]byte, []int) {
	return file_api_commission_service_v1_wallet_proto_rawDescGZIP(), []int{8}
}

type ListWalletReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wallets       []*GetWalletReply      `protobuf:"bytes,1,rep,name=wallets,proto3" json:"wallets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWalletReply) Reset() {
	*x = ListWalletReply{}
	mi := &file_api_commission_service_v1_wallet_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWalletReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWalletReply) ProtoMessage() {}

func (x *ListWalletReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_commission_service_v1_wallet_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWalletReply.ProtoReflect.Descriptor instead.
func (*ListWalletReply) Descriptor() ([]byte, []int) {
	return file_api_commission_service_v1_wallet_proto_rawDescGZIP(), []int{9}
}

func (x *ListWalletReply) GetWallets() []*GetWalletReply {
	if x != nil {
		return x.Wallets
	}
	return nil
}

type ListWalletByUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWalletByUserRequest) Reset() {
	*x = ListWalletByUserRequest{}
	mi := &file_api_commission_service_v1_wallet_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWalletByUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWalletByUserRequest) ProtoMessage() {}

func (x *ListWalletByUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_commission_service_v1_wallet_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWalletByUserRequest.ProtoReflect.Descriptor instead.
func (*ListWalletByUserRequest) Descriptor() ([]byte, []int) {
	return file_api_commission_service_v1_wallet_proto_rawDescGZIP(), []int{10}
}

func (x *ListWalletByUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_api_commission_service_v1_wallet_proto protoreflect.FileDescriptor

const file_api_commission_service_v1_wallet_proto_rawDesc = "" +
	"\n" +
	"&api/commission/service/v1/wallet.proto\x12\x19api.commission.service.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xca\x01\n" +
	"\x13CreateWalletRequest\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x06userId\x12;\n" +
	"\vwallet_type\x18\x02 \x01(\tB\x1a\xfaB\x17r\x15R\x06alipayR\x05wxpayR\x04tronR\n" +
	"walletType\x12\x1d\n" +
	"\aaccount\x18\x03 \x01(\tH\x00R\aaccount\x88\x01\x01\x12\x1c\n" +
	"\aqr_code\x18\x04 \x01(\tH\x01R\x06qrCode\x88\x01\x01B\n" +
	"\n" +
	"\b_accountB\n" +
	"\n" +
	"\b_qr_code\"\xed\x01\n" +
	"\x11CreateWalletReply\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vwallet_type\x18\x02 \x01(\tR\n" +
	"walletType\x12\x1d\n" +
	"\aaccount\x18\x03 \x01(\tH\x00R\aaccount\x88\x01\x01\x12\x1c\n" +
	"\aqr_code\x18\x04 \x01(\tH\x01R\x06qrCode\x88\x01\x01\x12\x0e\n" +
	"\x02id\x18\x05 \x01(\tR\x02id\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\n" +
	"\n" +
	"\b_accountB\n" +
	"\n" +
	"\b_qr_code\"\x84\x01\n" +
	"\x13UpdateWalletRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x02id\x12\x1d\n" +
	"\aaccount\x18\x03 \x01(\tH\x00R\aaccount\x88\x01\x01\x12\x1c\n" +
	"\aqr_code\x18\x04 \x01(\tH\x01R\x06qrCode\x88\x01\x01B\n" +
	"\n" +
	"\b_accountB\n" +
	"\n" +
	"\b_qr_code\"\xed\x01\n" +
	"\x11UpdateWalletReply\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vwallet_type\x18\x02 \x01(\tR\n" +
	"walletType\x12\x1d\n" +
	"\aaccount\x18\x03 \x01(\tH\x00R\aaccount\x88\x01\x01\x12\x1c\n" +
	"\aqr_code\x18\x04 \x01(\tH\x01R\x06qrCode\x88\x01\x01\x12\x0e\n" +
	"\x02id\x18\x05 \x01(\tR\x02id\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\n" +
	"\n" +
	"\b_accountB\n" +
	"\n" +
	"\b_qr_code\"/\n" +
	"\x13DeleteWalletRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x02id\"\x13\n" +
	"\x11DeleteWalletReply\",\n" +
	"\x10GetWalletRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x02id\"\xea\x01\n" +
	"\x0eGetWalletReply\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vwallet_type\x18\x02 \x01(\tR\n" +
	"walletType\x12\x1d\n" +
	"\aaccount\x18\x03 \x01(\tH\x00R\aaccount\x88\x01\x01\x12\x1c\n" +
	"\aqr_code\x18\x04 \x01(\tH\x01R\x06qrCode\x88\x01\x01\x12\x0e\n" +
	"\x02id\x18\x05 \x01(\tR\x02id\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\n" +
	"\n" +
	"\b_accountB\n" +
	"\n" +
	"\b_qr_code\"\x13\n" +
	"\x11ListWalletRequest\"V\n" +
	"\x0fListWalletReply\x12C\n" +
	"\awallets\x18\x01 \x03(\v2).api.commission.service.v1.GetWalletReplyR\awallets\"<\n" +
	"\x17ListWalletByUserRequest\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x06userId2\xca\x06\n" +
	"\x06Wallet\x12\x94\x01\n" +
	"\fCreateWallet\x12..api.commission.service.v1.CreateWalletRequest\x1a,.api.commission.service.v1.CreateWalletReply\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/v1/users/{user_id}/wallets\x12\x89\x01\n" +
	"\fUpdateWallet\x12..api.commission.service.v1.UpdateWalletRequest\x1a,.api.commission.service.v1.UpdateWalletReply\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*2\x10/v1/wallets/{id}\x12\x86\x01\n" +
	"\fDeleteWallet\x12..api.commission.service.v1.DeleteWalletRequest\x1a,.api.commission.service.v1.DeleteWalletReply\"\x18\x82\xd3\xe4\x93\x02\x12*\x10/v1/wallets/{id}\x12}\n" +
	"\tGetWallet\x12+.api.commission.service.v1.GetWalletRequest\x1a).api.commission.service.v1.GetWalletReply\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/wallets/{id}\x12{\n" +
	"\n" +
	"ListWallet\x12,.api.commission.service.v1.ListWalletRequest\x1a*.api.commission.service.v1.ListWalletReply\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/v1/wallets\x12\x97\x01\n" +
	"\x10ListWalletByUser\x122.api.commission.service.v1.ListWalletByUserRequest\x1a*.api.commission.service.v1.ListWalletReply\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/v1/users/{user_id}/walletsBB\n" +
	"\x19api.commission.service.v1P\x01Z#agents/api/commission/service/v1;v1b\x06proto3"

var (
	file_api_commission_service_v1_wallet_proto_rawDescOnce sync.Once
	file_api_commission_service_v1_wallet_proto_rawDescData []byte
)

func file_api_commission_service_v1_wallet_proto_rawDescGZIP() []byte {
	file_api_commission_service_v1_wallet_proto_rawDescOnce.Do(func() {
		file_api_commission_service_v1_wallet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_commission_service_v1_wallet_proto_rawDesc), len(file_api_commission_service_v1_wallet_proto_rawDesc)))
	})
	return file_api_commission_service_v1_wallet_proto_rawDescData
}

var file_api_commission_service_v1_wallet_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_commission_service_v1_wallet_proto_goTypes = []any{
	(*CreateWalletRequest)(nil),     // 0: api.commission.service.v1.CreateWalletRequest
	(*CreateWalletReply)(nil),       // 1: api.commission.service.v1.CreateWalletReply
	(*UpdateWalletRequest)(nil),     // 2: api.commission.service.v1.UpdateWalletRequest
	(*UpdateWalletReply)(nil),       // 3: api.commission.service.v1.UpdateWalletReply
	(*DeleteWalletRequest)(nil),     // 4: api.commission.service.v1.DeleteWalletRequest
	(*DeleteWalletReply)(nil),       // 5: api.commission.service.v1.DeleteWalletReply
	(*GetWalletRequest)(nil),        // 6: api.commission.service.v1.GetWalletRequest
	(*GetWalletReply)(nil),          // 7: api.commission.service.v1.GetWalletReply
	(*ListWalletRequest)(nil),       // 8: api.commission.service.v1.ListWalletRequest
	(*ListWalletReply)(nil),         // 9: api.commission.service.v1.ListWalletReply
	(*ListWalletByUserRequest)(nil), // 10: api.commission.service.v1.ListWalletByUserRequest
	(*timestamppb.Timestamp)(nil),   // 11: google.protobuf.Timestamp
}
var file_api_commission_service_v1_wallet_proto_depIdxs = []int32{
	11, // 0: api.commission.service.v1.CreateWalletReply.created_at:type_name -> google.protobuf.Timestamp
	11, // 1: api.commission.service.v1.UpdateWalletReply.created_at:type_name -> google.protobuf.Timestamp
	11, // 2: api.commission.service.v1.GetWalletReply.created_at:type_name -> google.protobuf.Timestamp
	7,  // 3: api.commission.service.v1.ListWalletReply.wallets:type_name -> api.commission.service.v1.GetWalletReply
	0,  // 4: api.commission.service.v1.Wallet.CreateWallet:input_type -> api.commission.service.v1.CreateWalletRequest
	2,  // 5: api.commission.service.v1.Wallet.UpdateWallet:input_type -> api.commission.service.v1.UpdateWalletRequest
	4,  // 6: api.commission.service.v1.Wallet.DeleteWallet:input_type -> api.commission.service.v1.DeleteWalletRequest
	6,  // 7: api.commission.service.v1.Wallet.GetWallet:input_type -> api.commission.service.v1.GetWalletRequest
	8,  // 8: api.commission.service.v1.Wallet.ListWallet:input_type -> api.commission.service.v1.ListWalletRequest
	10, // 9: api.commission.service.v1.Wallet.ListWalletByUser:input_type -> api.commission.service.v1.ListWalletByUserRequest
	1,  // 10: api.commission.service.v1.Wallet.CreateWallet:output_type -> api.commission.service.v1.CreateWalletReply
	3,  // 11: api.commission.service.v1.Wallet.UpdateWallet:output_type -> api.commission.service.v1.UpdateWalletReply
	5,  // 12: api.commission.service.v1.Wallet.DeleteWallet:output_type -> api.commission.service.v1.DeleteWalletReply
	7,  // 13: api.commission.service.v1.Wallet.GetWallet:output_type -> api.commission.service.v1.GetWalletReply
	9,  // 14: api.commission.service.v1.Wallet.ListWallet:output_type -> api.commission.service.v1.ListWalletReply
	9,  // 15: api.commission.service.v1.Wallet.ListWalletByUser:output_type -> api.commission.service.v1.ListWalletReply
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_commission_service_v1_wallet_proto_init() }
func file_api_commission_service_v1_wallet_proto_init() {
	if File_api_commission_service_v1_wallet_proto != nil {
		return
	}
	file_api_commission_service_v1_wallet_proto_msgTypes[0].OneofWrappers = []any{}
	file_api_commission_service_v1_wallet_proto_msgTypes[1].OneofWrappers = []any{}
	file_api_commission_service_v1_wallet_proto_msgTypes[2].OneofWrappers = []any{}
	file_api_commission_service_v1_wallet_proto_msgTypes[3].OneofWrappers = []any{}
	file_api_commission_service_v1_wallet_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_commission_service_v1_wallet_proto_rawDesc), len(file_api_commission_service_v1_wallet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_commission_service_v1_wallet_proto_goTypes,
		DependencyIndexes: file_api_commission_service_v1_wallet_proto_depIdxs,
		MessageInfos:      file_api_commission_service_v1_wallet_proto_msgTypes,
	}.Build()
	File_api_commission_service_v1_wallet_proto = out.File
	file_api_commission_service_v1_wallet_proto_goTypes = nil
	file_api_commission_service_v1_wallet_proto_depIdxs = nil
}
