// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"agents/app/user/service/internal/biz"
	"agents/app/user/service/internal/conf"
	"agents/app/user/service/internal/data"
	"agents/app/user/service/internal/server"
	"agents/app/user/service/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "github.com/go-sql-driver/mysql"
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger, registry *conf.Registry, auth *conf.Auth) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData, logger)
	userUseCase := biz.NewUserUseCase(userRepo, logger)
	userDomainRepo := data.NewUserDomainRepo(dataData, logger)
	userDomainUseCase := biz.NewUserDomainUseCase(userDomainRepo, logger)
	userService := service.NewUserService(userUseCase, userDomainUseCase)
	v := server.NewMiddlewares(logger)
	grpcServer := server.NewGRPCServer(confServer, userService, logger, v)
	httpServer := server.NewHTTPServer(confServer, logger, userService, v)
	registrar := server.NewRegistrar(registry)
	app := newApp(logger, grpcServer, httpServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
