registry:
  consul:
    address: consul:8500
    schema: http

data:
  database:
    migration_source: file:///migrations

auth:
  secret: "secret"
  public_key: "pb"
  token_duration: 3600s
  signing_method: "RS256"