// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"agents/app/authn/service/internal/biz"
	"agents/app/authn/service/internal/conf"
	"agents/app/authn/service/internal/data"
	"agents/app/authn/service/internal/server"
	"agents/app/authn/service/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger, auth *conf.Auth, registry *conf.Registry) (*kratos.App, func(), error) {
	db := data.NewSqlxClient(confData)
	discovery := data.NewDiscovery(registry)
	userClient := data.NewUserServiceClient(discovery)
	dataData, cleanup, err := data.NewData(confData, logger, db, userClient)
	if err != nil {
		return nil, nil, err
	}
	userCredentialRepo := data.NewUserCredentialRepo(dataData, logger)
	userRepo := data.NewUserRepo(dataData, logger)
	authUserCase := biz.NewAuthUserCase(userCredentialRepo, logger, userRepo, auth)
	authnService := service.NewAuthnService(authUserCase)
	grpcServer := server.NewGRPCServer(confServer, authnService, logger)
	httpServer := server.NewHTTPServer(confServer, logger, authnService)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
