// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.0--dev
// source: api/user/service/v1/user.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListUserByParentIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentId      string                 `protobuf:"bytes,1,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	OrderBy       string                 `protobuf:"bytes,3,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,6,opt,name=offset,proto3" json:"offset,omitempty"`
	Sort          string                 `protobuf:"bytes,7,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserByParentIdReq) Reset() {
	*x = ListUserByParentIdReq{}
	mi := &file_api_user_service_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserByParentIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserByParentIdReq) ProtoMessage() {}

func (x *ListUserByParentIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserByParentIdReq.ProtoReflect.Descriptor instead.
func (*ListUserByParentIdReq) Descriptor() ([]byte, []int) {
	return file_api_user_service_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *ListUserByParentIdReq) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *ListUserByParentIdReq) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

func (x *ListUserByParentIdReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListUserByParentIdReq) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListUserByParentIdReq) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

type ListUserByParentIdReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*GetUserReply        `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserByParentIdReply) Reset() {
	*x = ListUserByParentIdReply{}
	mi := &file_api_user_service_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserByParentIdReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserByParentIdReply) ProtoMessage() {}

func (x *ListUserByParentIdReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserByParentIdReply.ProtoReflect.Descriptor instead.
func (*ListUserByParentIdReply) Descriptor() ([]byte, []int) {
	return file_api_user_service_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *ListUserByParentIdReply) GetUsers() []*GetUserReply {
	if x != nil {
		return x.Users
	}
	return nil
}

type GetUserByDomainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByDomainRequest) Reset() {
	*x = GetUserByDomainRequest{}
	mi := &file_api_user_service_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByDomainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByDomainRequest) ProtoMessage() {}

func (x *GetUserByDomainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByDomainRequest.ProtoReflect.Descriptor instead.
func (*GetUserByDomainRequest) Descriptor() ([]byte, []int) {
	return file_api_user_service_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserByDomainRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type GetUserByDomainReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Level         int32                  `protobuf:"varint,5,opt,name=level,proto3" json:"level,omitempty"`
	SharePercent  float32                `protobuf:"fixed32,6,opt,name=share_percent,json=sharePercent,proto3" json:"share_percent,omitempty"`
	Nickname      *string                `protobuf:"bytes,7,opt,name=nickname,proto3,oneof" json:"nickname,omitempty"`
	ParentId      *string                `protobuf:"bytes,8,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByDomainReply) Reset() {
	*x = GetUserByDomainReply{}
	mi := &file_api_user_service_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByDomainReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByDomainReply) ProtoMessage() {}

func (x *GetUserByDomainReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByDomainReply.ProtoReflect.Descriptor instead.
func (*GetUserByDomainReply) Descriptor() ([]byte, []int) {
	return file_api_user_service_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserByDomainReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetUserByDomainReply) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetUserByDomainReply) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *GetUserByDomainReply) GetSharePercent() float32 {
	if x != nil {
		return x.SharePercent
	}
	return 0
}

func (x *GetUserByDomainReply) GetNickname() string {
	if x != nil && x.Nickname != nil {
		return *x.Nickname
	}
	return ""
}

func (x *GetUserByDomainReply) GetParentId() string {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return ""
}

type GetUserByUsernameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByUsernameRequest) Reset() {
	*x = GetUserByUsernameRequest{}
	mi := &file_api_user_service_v1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByUsernameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByUsernameRequest) ProtoMessage() {}

func (x *GetUserByUsernameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_v1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByUsernameRequest.ProtoReflect.Descriptor instead.
func (*GetUserByUsernameRequest) Descriptor() ([]byte, []int) {
	return file_api_user_service_v1_user_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserByUsernameRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type DeleteDomainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDomainRequest) Reset() {
	*x = DeleteDomainRequest{}
	mi := &file_api_user_service_v1_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDomainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDomainRequest) ProtoMessage() {}

func (x *DeleteDomainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_v1_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDomainRequest.ProtoReflect.Descriptor instead.
func (*DeleteDomainRequest) Descriptor() ([]byte, []int) {
	return file_api_user_service_v1_user_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteDomainRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteDomainReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDomainReply) Reset() {
	*x = DeleteDomainReply{}
	mi := &file_api_user_service_v1_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDomainReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDomainReply) ProtoMessage() {}

func (x *DeleteDomainReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_v1_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDomainReply.ProtoReflect.Descriptor instead.
func (*DeleteDomainReply) Descriptor() ([]byte, []int) {
	return file_api_user_service_v1_user_proto_rawDescGZIP(), []int{6}
}

type ListUserDomainsByUserIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserDomainsByUserIdRequest) Reset() {
	*x = ListUserDomainsByUserIdRequest{}
	mi := &file_api_user_service_v1_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserDomainsByUserIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserDomainsByUserIdRequest) ProtoMessage() {}

func (x *ListUserDomainsByUserIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_v1_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserDomainsByUserIdRequest.ProtoReflect.Descriptor instead.
func (*ListUserDomainsByUserIdRequest) Descriptor() ([]byte, []int) {
	return file_api_user_service_v1_user_proto_rawDescGZIP(), []int{7}
}

func (x *ListUserDomainsByUserIdRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListUserDomainsByUserIdReply struct {
	state         protoimpl.MessageState                 `protogen:"open.v1"`
	Domains       []*ListUserDomainsByUserIdReply_Domain `protobuf:"bytes,1,rep,name=domains,proto3" json:"domains,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserDomainsByUserIdReply) Reset() {
	*x = ListUserDomainsByUserIdReply{}
	mi := &file_api_user_service_v1_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserDomainsByUserIdReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserDomainsByUserIdReply) ProtoMessage() {}

func (x *ListUserDomainsByUserIdReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_v1_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserDomainsByUserIdReply.ProtoReflect.Descriptor instead.
func (*ListUserDomainsByUserIdReply) Descriptor() ([]byte, []int) {
	return file_api_user_service_v1_user_proto_rawDescGZIP(), []int{8}
}

func (x *ListUserDomainsByUserIdReply) GetDomains() []*ListUserDomainsByUserIdReply_Domain {
	if x != nil {
		return x.Domains
	}
	return nil
}

type ListUserDomainsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserDomainsRequest) Reset() {
	*x = ListUserDomainsRequest{}
	mi := &file_api_user_service_v1_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserDomainsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserDomainsRequest) ProtoMessage() {}

func (x *ListUserDomainsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_v1_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserDomainsRequest.ProtoReflect.Descriptor instead.
func (*ListUserDomainsRequest) Descriptor() ([]byte, []int) {
	return file_api_user_service_v1_user_proto_rawDescGZIP(), []int{9}
}

type ListUserDomainsReply struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Domains       []*ListUserDomainsReply_Domain `protobuf:"bytes,1,rep,name=domains,proto3" json:"domains,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserDomainsReply) Reset() {
	*x = ListUserDomainsReply{}
	mi := &file_api_user_service_v1_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserDomainsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserDomainsReply) ProtoMessage() {}

func (x *ListUserDomainsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_v1_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserDomainsReply.ProtoReflect.Descriptor instead.
func (*ListUserDomainsReply) Descriptor() ([]byte, []int) {
	return file_api_user_service_v1_user_proto_rawDescGZIP(), []int{10}
}

func (x *ListUserDomainsReply) GetDomains() []*ListUserDomainsReply_Domain {
	if x != nil {
		return x.Domains
	}
	return nil
}

type GetUserDomainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserDomainRequest) Reset() {
	*x = GetUserDomainRequest{}
	mi := &file_api_user_service_v1_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserDomainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserDomainRequest) ProtoMessage() {}

func (x *GetUserDomainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_v1_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserDomainRequest.ProtoReflect.Descriptor instead.
func (*GetUserDomainRequest) Descriptor() ([]byte, []int) {
	return file_api_user_service_v1_user_proto_rawDescGZIP(), []int{11}
}

func (x *GetUserDomainRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetUserDomainReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Domain        string                 `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserDomainReply) Reset() {
	*x = GetUserDomainReply{}
	mi := &file_api_user_service_v1_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserDomainReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserDomainReply) ProtoMessage() {}

func (x *GetUserDomainReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_v1_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserDomainReply.ProtoReflect.Descriptor instead.
func (*GetUserDomainReply) Descriptor() ([]byte, []int) {
	return file_api_user_service_v1_user_proto_rawDescGZIP(), []int{12}
}

func (x *GetUserDomainReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetUserDomainReply) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserDomainReply) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type CreateUserDomainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Domain        string                 `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserDomainRequest) Reset() {
	*x = CreateUserDomainRequest{}
	mi := &file_api_user_service_v1_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserDomainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserDomainRequest) ProtoMessage() {}

func (x *CreateUserDomainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_v1_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserDomainRequest.ProtoReflect.Descriptor instead.
func (*CreateUserDomainRequest) Descriptor() ([]byte, []int) {
	return file_api_user_service_v1_user_proto_rawDescGZIP(), []int{13}
}

func (x *CreateUserDomainRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateUserDomainRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type CreateUserDomainReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Domain        string                 `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserDomainReply) Reset() {
	*x = CreateUserDomainReply{}
	mi := &file_api_user_service_v1_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserDomainReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserDomainReply) ProtoMessage() {}

func (x *CreateUserDomainReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_v1_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserDomainReply.ProtoReflect.Descriptor instead.
func (*CreateUserDomainReply) Descriptor() ([]byte, []int) {
	return file_api_user_service_v1_user_proto_rawDescGZIP(), []int{14}
}

func (x *CreateUserDomainReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateUserDomainReply) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateUserDomainReply) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Nickname      *string                `protobuf:"bytes,4,opt,name=nickname,proto3,oneof" json:"nickname,omitempty"`
	ParentId      *string                `protobuf:"bytes,5,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	Level         int32                  `protobuf:"varint,6,opt,name=level,proto3" json:"level,omitempty"`
	SharePercent  float32                `protobuf:"fixed32,7,opt,name=share_percent,json=sharePercent,proto3" json:"share_percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_api_user_service_v1_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_v1_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_api_user_service_v1_user_proto_rawDescGZIP(), []int{15}
}

func (x *CreateUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateUserRequest) GetNickname() string {
	if x != nil && x.Nickname != nil {
		return *x.Nickname
	}
	return ""
}

func (x *CreateUserRequest) GetParentId() string {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return ""
}

func (x *CreateUserRequest) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *CreateUserRequest) GetSharePercent() float32 {
	if x != nil {
		return x.SharePercent
	}
	return 0
}

type CreateUserReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Level         int32                  `protobuf:"varint,5,opt,name=level,proto3" json:"level,omitempty"`
	SharePercent  float32                `protobuf:"fixed32,6,opt,name=share_percent,json=sharePercent,proto3" json:"share_percent,omitempty"`
	Nickname      *string                `protobuf:"bytes,7,opt,name=nickname,proto3,oneof" json:"nickname,omitempty"`
	ParentId      *string                `protobuf:"bytes,8,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserReply) Reset() {
	*x = CreateUserReply{}
	mi := &file_api_user_service_v1_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserReply) ProtoMessage() {}

func (x *CreateUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_v1_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserReply.ProtoReflect.Descriptor instead.
func (*CreateUserReply) Descriptor() ([]byte, []int) {
	return file_api_user_service_v1_user_proto_rawDescGZIP(), []int{16}
}

func (x *CreateUserReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateUserReply) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateUserReply) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *CreateUserReply) GetSharePercent() float32 {
	if x != nil {
		return x.SharePercent
	}
	return 0
}

func (x *CreateUserReply) GetNickname() string {
	if x != nil && x.Nickname != nil {
		return *x.Nickname
	}
	return ""
}

func (x *CreateUserReply) GetParentId() string {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return ""
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Password      *string                `protobuf:"bytes,3,opt,name=password,proto3,oneof" json:"password,omitempty"`
	Nickname      *string                `protobuf:"bytes,4,opt,name=nickname,proto3,oneof" json:"nickname,omitempty"`
	SharePercent  *float32               `protobuf:"fixed32,5,opt,name=share_percent,json=sharePercent,proto3,oneof" json:"share_percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_api_user_service_v1_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_v1_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_api_user_service_v1_user_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateUserRequest) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

func (x *UpdateUserRequest) GetNickname() string {
	if x != nil && x.Nickname != nil {
		return *x.Nickname
	}
	return ""
}

func (x *UpdateUserRequest) GetSharePercent() float32 {
	if x != nil && x.SharePercent != nil {
		return *x.SharePercent
	}
	return 0
}

type UpdateUserReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Level         int32                  `protobuf:"varint,5,opt,name=level,proto3" json:"level,omitempty"`
	SharePercent  float32                `protobuf:"fixed32,6,opt,name=share_percent,json=sharePercent,proto3" json:"share_percent,omitempty"`
	Nickname      *string                `protobuf:"bytes,7,opt,name=nickname,proto3,oneof" json:"nickname,omitempty"`
	ParentId      *string                `protobuf:"bytes,8,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserReply) Reset() {
	*x = UpdateUserReply{}
	mi := &file_api_user_service_v1_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserReply) ProtoMessage() {}

func (x *UpdateUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_v1_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserReply.ProtoReflect.Descriptor instead.
func (*UpdateUserReply) Descriptor() ([]byte, []int) {
	return file_api_user_service_v1_user_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateUserReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateUserReply) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UpdateUserReply) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *UpdateUserReply) GetSharePercent() float32 {
	if x != nil {
		return x.SharePercent
	}
	return 0
}

func (x *UpdateUserReply) GetNickname() string {
	if x != nil && x.Nickname != nil {
		return *x.Nickname
	}
	return ""
}

func (x *UpdateUserReply) GetParentId() string {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return ""
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_api_user_service_v1_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_v1_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_api_user_service_v1_user_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteUserReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserReply) Reset() {
	*x = DeleteUserReply{}
	mi := &file_api_user_service_v1_user_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserReply) ProtoMessage() {}

func (x *DeleteUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_v1_user_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserReply.ProtoReflect.Descriptor instead.
func (*DeleteUserReply) Descriptor() ([]byte, []int) {
	return file_api_user_service_v1_user_proto_rawDescGZIP(), []int{20}
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_api_user_service_v1_user_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_v1_user_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_api_user_service_v1_user_proto_rawDescGZIP(), []int{21}
}

func (x *GetUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetUserReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Level         int32                  `protobuf:"varint,5,opt,name=level,proto3" json:"level,omitempty"`
	SharePercent  float32                `protobuf:"fixed32,6,opt,name=share_percent,json=sharePercent,proto3" json:"share_percent,omitempty"`
	Nickname      *string                `protobuf:"bytes,7,opt,name=nickname,proto3,oneof" json:"nickname,omitempty"`
	ParentId      *string                `protobuf:"bytes,8,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserReply) Reset() {
	*x = GetUserReply{}
	mi := &file_api_user_service_v1_user_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserReply) ProtoMessage() {}

func (x *GetUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_v1_user_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserReply.ProtoReflect.Descriptor instead.
func (*GetUserReply) Descriptor() ([]byte, []int) {
	return file_api_user_service_v1_user_proto_rawDescGZIP(), []int{22}
}

func (x *GetUserReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetUserReply) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetUserReply) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *GetUserReply) GetSharePercent() float32 {
	if x != nil {
		return x.SharePercent
	}
	return 0
}

func (x *GetUserReply) GetNickname() string {
	if x != nil && x.Nickname != nil {
		return *x.Nickname
	}
	return ""
}

func (x *GetUserReply) GetParentId() string {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return ""
}

type ListUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserRequest) Reset() {
	*x = ListUserRequest{}
	mi := &file_api_user_service_v1_user_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserRequest) ProtoMessage() {}

func (x *ListUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_v1_user_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserRequest.ProtoReflect.Descriptor instead.
func (*ListUserRequest) Descriptor() ([]byte, []int) {
	return file_api_user_service_v1_user_proto_rawDescGZIP(), []int{23}
}

type ListUserReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*ListUserReply_User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserReply) Reset() {
	*x = ListUserReply{}
	mi := &file_api_user_service_v1_user_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserReply) ProtoMessage() {}

func (x *ListUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_v1_user_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserReply.ProtoReflect.Descriptor instead.
func (*ListUserReply) Descriptor() ([]byte, []int) {
	return file_api_user_service_v1_user_proto_rawDescGZIP(), []int{24}
}

func (x *ListUserReply) GetUsers() []*ListUserReply_User {
	if x != nil {
		return x.Users
	}
	return nil
}

type ListUserDomainsByUserIdReply_Domain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Domain        string                 `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserDomainsByUserIdReply_Domain) Reset() {
	*x = ListUserDomainsByUserIdReply_Domain{}
	mi := &file_api_user_service_v1_user_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserDomainsByUserIdReply_Domain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserDomainsByUserIdReply_Domain) ProtoMessage() {}

func (x *ListUserDomainsByUserIdReply_Domain) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_v1_user_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserDomainsByUserIdReply_Domain.ProtoReflect.Descriptor instead.
func (*ListUserDomainsByUserIdReply_Domain) Descriptor() ([]byte, []int) {
	return file_api_user_service_v1_user_proto_rawDescGZIP(), []int{8, 0}
}

func (x *ListUserDomainsByUserIdReply_Domain) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ListUserDomainsByUserIdReply_Domain) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListUserDomainsByUserIdReply_Domain) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type ListUserDomainsReply_Domain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Domain        string                 `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserDomainsReply_Domain) Reset() {
	*x = ListUserDomainsReply_Domain{}
	mi := &file_api_user_service_v1_user_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserDomainsReply_Domain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserDomainsReply_Domain) ProtoMessage() {}

func (x *ListUserDomainsReply_Domain) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_v1_user_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserDomainsReply_Domain.ProtoReflect.Descriptor instead.
func (*ListUserDomainsReply_Domain) Descriptor() ([]byte, []int) {
	return file_api_user_service_v1_user_proto_rawDescGZIP(), []int{10, 0}
}

func (x *ListUserDomainsReply_Domain) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ListUserDomainsReply_Domain) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListUserDomainsReply_Domain) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type ListUserReply_User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	ParentId      string                 `protobuf:"bytes,4,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Level         int32                  `protobuf:"varint,5,opt,name=level,proto3" json:"level,omitempty"`
	SharePercent  float32                `protobuf:"fixed32,6,opt,name=share_percent,json=sharePercent,proto3" json:"share_percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserReply_User) Reset() {
	*x = ListUserReply_User{}
	mi := &file_api_user_service_v1_user_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserReply_User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserReply_User) ProtoMessage() {}

func (x *ListUserReply_User) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_service_v1_user_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserReply_User.ProtoReflect.Descriptor instead.
func (*ListUserReply_User) Descriptor() ([]byte, []int) {
	return file_api_user_service_v1_user_proto_rawDescGZIP(), []int{24, 0}
}

func (x *ListUserReply_User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ListUserReply_User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ListUserReply_User) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *ListUserReply_User) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *ListUserReply_User) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *ListUserReply_User) GetSharePercent() float32 {
	if x != nil {
		return x.SharePercent
	}
	return 0
}

var File_api_user_service_v1_user_proto protoreflect.FileDescriptor

const file_api_user_service_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/user/service/v1/user.proto\x12\x13api.user.service.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\"\xc4\x01\n" +
	"\x15ListUserByParentIdReq\x12%\n" +
	"\tparent_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\bparentId\x12.\n" +
	"\border_by\x18\x03 \x01(\tB\x13\xfaB\x10r\x0eR\x00R\n" +
	"created_atR\aorderBy\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x06 \x01(\x05R\x06offset\x12&\n" +
	"\x04sort\x18\a \x01(\tB\x12\xfaB\x0fr\rR\x00R\x03ascR\x04descR\x04sort\"R\n" +
	"\x17ListUserByParentIdReply\x127\n" +
	"\x05users\x18\x01 \x03(\v2!.api.user.service.v1.GetUserReplyR\x05users\"9\n" +
	"\x16GetUserByDomainRequest\x12\x1f\n" +
	"\x06domain\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x06domain\"\xe7\x01\n" +
	"\x14GetUserByDomainReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05level\x18\x05 \x01(\x05R\x05level\x12#\n" +
	"\rshare_percent\x18\x06 \x01(\x02R\fsharePercent\x12\x1f\n" +
	"\bnickname\x18\a \x01(\tH\x00R\bnickname\x88\x01\x01\x12 \n" +
	"\tparent_id\x18\b \x01(\tH\x01R\bparentId\x88\x01\x01B\v\n" +
	"\t_nicknameB\f\n" +
	"\n" +
	"_parent_idJ\x04\b\x03\x10\x04J\x04\b\x04\x10\x05\"6\n" +
	"\x18GetUserByUsernameRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"%\n" +
	"\x13DeleteDomainRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x13\n" +
	"\x11DeleteDomainReply\"9\n" +
	"\x1eListUserDomainsByUserIdRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xbd\x01\n" +
	"\x1cListUserDomainsByUserIdReply\x12R\n" +
	"\adomains\x18\x01 \x03(\v28.api.user.service.v1.ListUserDomainsByUserIdReply.DomainR\adomains\x1aI\n" +
	"\x06Domain\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\"\x18\n" +
	"\x16ListUserDomainsRequest\"\xad\x01\n" +
	"\x14ListUserDomainsReply\x12J\n" +
	"\adomains\x18\x01 \x03(\v20.api.user.service.v1.ListUserDomainsReply.DomainR\adomains\x1aI\n" +
	"\x06Domain\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\"&\n" +
	"\x14GetUserDomainRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"U\n" +
	"\x12GetUserDomainReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\"J\n" +
	"\x17CreateUserDomainRequest\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\"X\n" +
	"\x15CreateUserDomainReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\"\xc8\x01\n" +
	"\x11CreateUserRequest\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1f\n" +
	"\bnickname\x18\x04 \x01(\tH\x00R\bnickname\x88\x01\x01\x12 \n" +
	"\tparent_id\x18\x05 \x01(\tH\x01R\bparentId\x88\x01\x01\x12\x14\n" +
	"\x05level\x18\x06 \x01(\x05R\x05level\x12#\n" +
	"\rshare_percent\x18\a \x01(\x02R\fsharePercentB\v\n" +
	"\t_nicknameB\f\n" +
	"\n" +
	"_parent_id\"\xe2\x01\n" +
	"\x0fCreateUserReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05level\x18\x05 \x01(\x05R\x05level\x12#\n" +
	"\rshare_percent\x18\x06 \x01(\x02R\fsharePercent\x12\x1f\n" +
	"\bnickname\x18\a \x01(\tH\x00R\bnickname\x88\x01\x01\x12 \n" +
	"\tparent_id\x18\b \x01(\tH\x01R\bparentId\x88\x01\x01B\v\n" +
	"\t_nicknameB\f\n" +
	"\n" +
	"_parent_idJ\x04\b\x03\x10\x04J\x04\b\x04\x10\x05\"\xcf\x01\n" +
	"\x11UpdateUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12*\n" +
	"\bpassword\x18\x03 \x01(\tB\t\xfaB\x06r\x04\x10\b\x18\x14H\x00R\bpassword\x88\x01\x01\x12(\n" +
	"\bnickname\x18\x04 \x01(\tB\a\xfaB\x04r\x02\x18\x14H\x01R\bnickname\x88\x01\x01\x12(\n" +
	"\rshare_percent\x18\x05 \x01(\x02H\x02R\fsharePercent\x88\x01\x01B\v\n" +
	"\t_passwordB\v\n" +
	"\t_nicknameB\x10\n" +
	"\x0e_share_percent\"\xe2\x01\n" +
	"\x0fUpdateUserReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05level\x18\x05 \x01(\x05R\x05level\x12#\n" +
	"\rshare_percent\x18\x06 \x01(\x02R\fsharePercent\x12\x1f\n" +
	"\bnickname\x18\a \x01(\tH\x00R\bnickname\x88\x01\x01\x12 \n" +
	"\tparent_id\x18\b \x01(\tH\x01R\bparentId\x88\x01\x01B\v\n" +
	"\t_nicknameB\f\n" +
	"\n" +
	"_parent_idJ\x04\b\x03\x10\x04J\x04\b\x04\x10\x05\"#\n" +
	"\x11DeleteUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x11\n" +
	"\x0fDeleteUserReply\" \n" +
	"\x0eGetUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xdf\x01\n" +
	"\fGetUserReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05level\x18\x05 \x01(\x05R\x05level\x12#\n" +
	"\rshare_percent\x18\x06 \x01(\x02R\fsharePercent\x12\x1f\n" +
	"\bnickname\x18\a \x01(\tH\x00R\bnickname\x88\x01\x01\x12 \n" +
	"\tparent_id\x18\b \x01(\tH\x01R\bparentId\x88\x01\x01B\v\n" +
	"\t_nicknameB\f\n" +
	"\n" +
	"_parent_idJ\x04\b\x03\x10\x04J\x04\b\x04\x10\x05\"\x11\n" +
	"\x0fListUserRequest\"\xf7\x01\n" +
	"\rListUserReply\x12=\n" +
	"\x05users\x18\x01 \x03(\v2'.api.user.service.v1.ListUserReply.UserR\x05users\x1a\xa6\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x1b\n" +
	"\tparent_id\x18\x04 \x01(\tR\bparentId\x12\x14\n" +
	"\x05level\x18\x05 \x01(\x05R\x05level\x12#\n" +
	"\rshare_percent\x18\x06 \x01(\x02R\fsharePercent2\xdd\f\n" +
	"\x04User\x12p\n" +
	"\n" +
	"CreateUser\x12&.api.user.service.v1.CreateUserRequest\x1a$.api.user.service.v1.CreateUserReply\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/users\x12u\n" +
	"\n" +
	"UpdateUser\x12&.api.user.service.v1.UpdateUserRequest\x1a$.api.user.service.v1.UpdateUserReply\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*2\x0e/v1/users/{id}\x12r\n" +
	"\n" +
	"DeleteUser\x12&.api.user.service.v1.DeleteUserRequest\x1a$.api.user.service.v1.DeleteUserReply\"\x16\x82\xd3\xe4\x93\x02\x10*\x0e/v1/users/{id}\x12i\n" +
	"\aGetUser\x12#.api.user.service.v1.GetUserRequest\x1a!.api.user.service.v1.GetUserReply\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/users/{id}\x12g\n" +
	"\bListUser\x12$.api.user.service.v1.ListUserRequest\x1a\".api.user.service.v1.ListUserReply\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/users\x12e\n" +
	"\x11GetUserByUsername\x12-.api.user.service.v1.GetUserByUsernameRequest\x1a!.api.user.service.v1.GetUserReply\x12\x94\x01\n" +
	"\x10CreateUserDomain\x12,.api.user.service.v1.CreateUserDomainRequest\x1a*.api.user.service.v1.CreateUserDomainReply\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/v1/users/{user_id}/domains\x12\x96\x01\n" +
	"\x12ListUserByParentId\x12*.api.user.service.v1.ListUserByParentIdReq\x1a,.api.user.service.v1.ListUserByParentIdReply\"&\x82\xd3\xe4\x93\x02 \x12\x1e/v1/users/{parent_id}/children\x12}\n" +
	"\rGetUserDomain\x12).api.user.service.v1.GetUserDomainRequest\x1a'.api.user.service.v1.GetUserDomainReply\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/domains/{id}\x12~\n" +
	"\x0fListUserDomains\x12+.api.user.service.v1.ListUserDomainsRequest\x1a).api.user.service.v1.ListUserDomainsReply\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/v1/domains\x12\xa6\x01\n" +
	"\x17ListUserDomainsByUserId\x123.api.user.service.v1.ListUserDomainsByUserIdRequest\x1a1.api.user.service.v1.ListUserDomainsByUserIdReply\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/v1/users/{user_id}/domains\x12z\n" +
	"\fDeleteDomain\x12(.api.user.service.v1.DeleteDomainRequest\x1a&.api.user.service.v1.DeleteDomainReply\"\x18\x82\xd3\xe4\x93\x02\x12*\x10/v1/domains/{id}\x12i\n" +
	"\x0fGetUserByDomain\x12+.api.user.service.v1.GetUserByDomainRequest\x1a).api.user.service.v1.GetUserByDomainReplyB6\n" +
	"\x13api.user.service.v1P\x01Z\x1dagents/api/user/service/v1;v1b\x06proto3"

var (
	file_api_user_service_v1_user_proto_rawDescOnce sync.Once
	file_api_user_service_v1_user_proto_rawDescData []byte
)

func file_api_user_service_v1_user_proto_rawDescGZIP() []byte {
	file_api_user_service_v1_user_proto_rawDescOnce.Do(func() {
		file_api_user_service_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_user_service_v1_user_proto_rawDesc), len(file_api_user_service_v1_user_proto_rawDesc)))
	})
	return file_api_user_service_v1_user_proto_rawDescData
}

var file_api_user_service_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_api_user_service_v1_user_proto_goTypes = []any{
	(*ListUserByParentIdReq)(nil),               // 0: api.user.service.v1.ListUserByParentIdReq
	(*ListUserByParentIdReply)(nil),             // 1: api.user.service.v1.ListUserByParentIdReply
	(*GetUserByDomainRequest)(nil),              // 2: api.user.service.v1.GetUserByDomainRequest
	(*GetUserByDomainReply)(nil),                // 3: api.user.service.v1.GetUserByDomainReply
	(*GetUserByUsernameRequest)(nil),            // 4: api.user.service.v1.GetUserByUsernameRequest
	(*DeleteDomainRequest)(nil),                 // 5: api.user.service.v1.DeleteDomainRequest
	(*DeleteDomainReply)(nil),                   // 6: api.user.service.v1.DeleteDomainReply
	(*ListUserDomainsByUserIdRequest)(nil),      // 7: api.user.service.v1.ListUserDomainsByUserIdRequest
	(*ListUserDomainsByUserIdReply)(nil),        // 8: api.user.service.v1.ListUserDomainsByUserIdReply
	(*ListUserDomainsRequest)(nil),              // 9: api.user.service.v1.ListUserDomainsRequest
	(*ListUserDomainsReply)(nil),                // 10: api.user.service.v1.ListUserDomainsReply
	(*GetUserDomainRequest)(nil),                // 11: api.user.service.v1.GetUserDomainRequest
	(*GetUserDomainReply)(nil),                  // 12: api.user.service.v1.GetUserDomainReply
	(*CreateUserDomainRequest)(nil),             // 13: api.user.service.v1.CreateUserDomainRequest
	(*CreateUserDomainReply)(nil),               // 14: api.user.service.v1.CreateUserDomainReply
	(*CreateUserRequest)(nil),                   // 15: api.user.service.v1.CreateUserRequest
	(*CreateUserReply)(nil),                     // 16: api.user.service.v1.CreateUserReply
	(*UpdateUserRequest)(nil),                   // 17: api.user.service.v1.UpdateUserRequest
	(*UpdateUserReply)(nil),                     // 18: api.user.service.v1.UpdateUserReply
	(*DeleteUserRequest)(nil),                   // 19: api.user.service.v1.DeleteUserRequest
	(*DeleteUserReply)(nil),                     // 20: api.user.service.v1.DeleteUserReply
	(*GetUserRequest)(nil),                      // 21: api.user.service.v1.GetUserRequest
	(*GetUserReply)(nil),                        // 22: api.user.service.v1.GetUserReply
	(*ListUserRequest)(nil),                     // 23: api.user.service.v1.ListUserRequest
	(*ListUserReply)(nil),                       // 24: api.user.service.v1.ListUserReply
	(*ListUserDomainsByUserIdReply_Domain)(nil), // 25: api.user.service.v1.ListUserDomainsByUserIdReply.Domain
	(*ListUserDomainsReply_Domain)(nil),         // 26: api.user.service.v1.ListUserDomainsReply.Domain
	(*ListUserReply_User)(nil),                  // 27: api.user.service.v1.ListUserReply.User
}
var file_api_user_service_v1_user_proto_depIdxs = []int32{
	22, // 0: api.user.service.v1.ListUserByParentIdReply.users:type_name -> api.user.service.v1.GetUserReply
	25, // 1: api.user.service.v1.ListUserDomainsByUserIdReply.domains:type_name -> api.user.service.v1.ListUserDomainsByUserIdReply.Domain
	26, // 2: api.user.service.v1.ListUserDomainsReply.domains:type_name -> api.user.service.v1.ListUserDomainsReply.Domain
	27, // 3: api.user.service.v1.ListUserReply.users:type_name -> api.user.service.v1.ListUserReply.User
	15, // 4: api.user.service.v1.User.CreateUser:input_type -> api.user.service.v1.CreateUserRequest
	17, // 5: api.user.service.v1.User.UpdateUser:input_type -> api.user.service.v1.UpdateUserRequest
	19, // 6: api.user.service.v1.User.DeleteUser:input_type -> api.user.service.v1.DeleteUserRequest
	21, // 7: api.user.service.v1.User.GetUser:input_type -> api.user.service.v1.GetUserRequest
	23, // 8: api.user.service.v1.User.ListUser:input_type -> api.user.service.v1.ListUserRequest
	4,  // 9: api.user.service.v1.User.GetUserByUsername:input_type -> api.user.service.v1.GetUserByUsernameRequest
	13, // 10: api.user.service.v1.User.CreateUserDomain:input_type -> api.user.service.v1.CreateUserDomainRequest
	0,  // 11: api.user.service.v1.User.ListUserByParentId:input_type -> api.user.service.v1.ListUserByParentIdReq
	11, // 12: api.user.service.v1.User.GetUserDomain:input_type -> api.user.service.v1.GetUserDomainRequest
	9,  // 13: api.user.service.v1.User.ListUserDomains:input_type -> api.user.service.v1.ListUserDomainsRequest
	7,  // 14: api.user.service.v1.User.ListUserDomainsByUserId:input_type -> api.user.service.v1.ListUserDomainsByUserIdRequest
	5,  // 15: api.user.service.v1.User.DeleteDomain:input_type -> api.user.service.v1.DeleteDomainRequest
	2,  // 16: api.user.service.v1.User.GetUserByDomain:input_type -> api.user.service.v1.GetUserByDomainRequest
	16, // 17: api.user.service.v1.User.CreateUser:output_type -> api.user.service.v1.CreateUserReply
	18, // 18: api.user.service.v1.User.UpdateUser:output_type -> api.user.service.v1.UpdateUserReply
	20, // 19: api.user.service.v1.User.DeleteUser:output_type -> api.user.service.v1.DeleteUserReply
	22, // 20: api.user.service.v1.User.GetUser:output_type -> api.user.service.v1.GetUserReply
	24, // 21: api.user.service.v1.User.ListUser:output_type -> api.user.service.v1.ListUserReply
	22, // 22: api.user.service.v1.User.GetUserByUsername:output_type -> api.user.service.v1.GetUserReply
	14, // 23: api.user.service.v1.User.CreateUserDomain:output_type -> api.user.service.v1.CreateUserDomainReply
	1,  // 24: api.user.service.v1.User.ListUserByParentId:output_type -> api.user.service.v1.ListUserByParentIdReply
	12, // 25: api.user.service.v1.User.GetUserDomain:output_type -> api.user.service.v1.GetUserDomainReply
	10, // 26: api.user.service.v1.User.ListUserDomains:output_type -> api.user.service.v1.ListUserDomainsReply
	8,  // 27: api.user.service.v1.User.ListUserDomainsByUserId:output_type -> api.user.service.v1.ListUserDomainsByUserIdReply
	6,  // 28: api.user.service.v1.User.DeleteDomain:output_type -> api.user.service.v1.DeleteDomainReply
	3,  // 29: api.user.service.v1.User.GetUserByDomain:output_type -> api.user.service.v1.GetUserByDomainReply
	17, // [17:30] is the sub-list for method output_type
	4,  // [4:17] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_user_service_v1_user_proto_init() }
func file_api_user_service_v1_user_proto_init() {
	if File_api_user_service_v1_user_proto != nil {
		return
	}
	file_api_user_service_v1_user_proto_msgTypes[3].OneofWrappers = []any{}
	file_api_user_service_v1_user_proto_msgTypes[15].OneofWrappers = []any{}
	file_api_user_service_v1_user_proto_msgTypes[16].OneofWrappers = []any{}
	file_api_user_service_v1_user_proto_msgTypes[17].OneofWrappers = []any{}
	file_api_user_service_v1_user_proto_msgTypes[18].OneofWrappers = []any{}
	file_api_user_service_v1_user_proto_msgTypes[22].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_user_service_v1_user_proto_rawDesc), len(file_api_user_service_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_user_service_v1_user_proto_goTypes,
		DependencyIndexes: file_api_user_service_v1_user_proto_depIdxs,
		MessageInfos:      file_api_user_service_v1_user_proto_msgTypes,
	}.Build()
	File_api_user_service_v1_user_proto = out.File
	file_api_user_service_v1_user_proto_goTypes = nil
	file_api_user_service_v1_user_proto_depIdxs = nil
}
