registry:
  consul:
    address: consul:8500
    schema: http

data:
  database:
    migration_source: file:///migrations

auth:
  secret: "/data/conf/dev/private.pem"
  public_key: "/data/conf/dev/public.pem"
  token_duration: 3600s
  signing_method: "RS256"