ALTER TABLE user_credentials ADD COLUMN alg VARCHAR(10) NOT NULL DEFAULT 'RS256',
  ADD COLUMN public_key TEXT NULL,
  ADD COLUMN private_key TEXT NULL,
  ADD COLUMN secret TEXT NULL,
  ADD COLUMN token_key TEXT NOT NULL;