// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.0--dev
// source: api/authn/service/v1/authn.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Username      *string                `protobuf:"bytes,2,opt,name=username,proto3,oneof" json:"username,omitempty"`
	Nickname      *string                `protobuf:"bytes,3,opt,name=nickname,proto3,oneof" json:"nickname,omitempty"`
	ParentId      *string                `protobuf:"bytes,4,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	Level         *int32                 `protobuf:"varint,5,opt,name=level,proto3,oneof" json:"level,omitempty"`
	SharePercent  float32                `protobuf:"fixed32,6,opt,name=share_percent,json=sharePercent,proto3" json:"share_percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_api_authn_service_v1_authn_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_authn_service_v1_authn_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_api_authn_service_v1_authn_proto_rawDescGZIP(), []int{0}
}

func (x *UserInfo) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *UserInfo) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *UserInfo) GetNickname() string {
	if x != nil && x.Nickname != nil {
		return *x.Nickname
	}
	return ""
}

func (x *UserInfo) GetParentId() string {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return ""
}

func (x *UserInfo) GetLevel() int32 {
	if x != nil && x.Level != nil {
		return *x.Level
	}
	return 0
}

func (x *UserInfo) GetSharePercent() float32 {
	if x != nil {
		return x.SharePercent
	}
	return 0
}

type AuthReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         *string                `protobuf:"bytes,1,opt,name=token,proto3,oneof" json:"token,omitempty"`
	User          *UserInfo              `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthReply) Reset() {
	*x = AuthReply{}
	mi := &file_api_authn_service_v1_authn_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthReply) ProtoMessage() {}

func (x *AuthReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_authn_service_v1_authn_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthReply.ProtoReflect.Descriptor instead.
func (*AuthReply) Descriptor() ([]byte, []int) {
	return file_api_authn_service_v1_authn_proto_rawDescGZIP(), []int{1}
}

func (x *AuthReply) GetToken() string {
	if x != nil && x.Token != nil {
		return *x.Token
	}
	return ""
}

func (x *AuthReply) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      *string                `protobuf:"bytes,1,opt,name=username,proto3,oneof" json:"username,omitempty"`
	Password      *string                `protobuf:"bytes,2,opt,name=password,proto3,oneof" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_api_authn_service_v1_authn_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_authn_service_v1_authn_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_api_authn_service_v1_authn_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

type VerifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         *string                `protobuf:"bytes,1,opt,name=token,proto3,oneof" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyRequest) Reset() {
	*x = VerifyRequest{}
	mi := &file_api_authn_service_v1_authn_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyRequest) ProtoMessage() {}

func (x *VerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_authn_service_v1_authn_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyRequest.ProtoReflect.Descriptor instead.
func (*VerifyRequest) Descriptor() ([]byte, []int) {
	return file_api_authn_service_v1_authn_proto_rawDescGZIP(), []int{3}
}

func (x *VerifyRequest) GetToken() string {
	if x != nil && x.Token != nil {
		return *x.Token
	}
	return ""
}

type VerifyReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserInfo              `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyReply) Reset() {
	*x = VerifyReply{}
	mi := &file_api_authn_service_v1_authn_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyReply) ProtoMessage() {}

func (x *VerifyReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_authn_service_v1_authn_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyReply.ProtoReflect.Descriptor instead.
func (*VerifyReply) Descriptor() ([]byte, []int) {
	return file_api_authn_service_v1_authn_proto_rawDescGZIP(), []int{4}
}

func (x *VerifyReply) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      *string                `protobuf:"bytes,1,opt,name=username,proto3,oneof" json:"username,omitempty"`
	Password      *string                `protobuf:"bytes,2,opt,name=password,proto3,oneof" json:"password,omitempty"`
	Nickname      *string                `protobuf:"bytes,3,opt,name=nickname,proto3,oneof" json:"nickname,omitempty"`
	ParentId      *string                `protobuf:"bytes,4,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	Level         *int32                 `protobuf:"varint,5,opt,name=level,proto3,oneof" json:"level,omitempty"`
	SharePercent  float32                `protobuf:"fixed32,6,opt,name=share_percent,json=sharePercent,proto3" json:"share_percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_api_authn_service_v1_authn_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_authn_service_v1_authn_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_api_authn_service_v1_authn_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

func (x *RegisterRequest) GetNickname() string {
	if x != nil && x.Nickname != nil {
		return *x.Nickname
	}
	return ""
}

func (x *RegisterRequest) GetParentId() string {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return ""
}

func (x *RegisterRequest) GetLevel() int32 {
	if x != nil && x.Level != nil {
		return *x.Level
	}
	return 0
}

func (x *RegisterRequest) GetSharePercent() float32 {
	if x != nil {
		return x.SharePercent
	}
	return 0
}

var File_api_authn_service_v1_authn_proto protoreflect.FileDescriptor

const file_api_authn_service_v1_authn_proto_rawDesc = "" +
	"\n" +
	" api/authn/service/v1/authn.proto\x12\x14api.authn.service.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\"\xfc\x01\n" +
	"\bUserInfo\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12\x1f\n" +
	"\busername\x18\x02 \x01(\tH\x01R\busername\x88\x01\x01\x12\x1f\n" +
	"\bnickname\x18\x03 \x01(\tH\x02R\bnickname\x88\x01\x01\x12 \n" +
	"\tparent_id\x18\x04 \x01(\tH\x03R\bparentId\x88\x01\x01\x12\x19\n" +
	"\x05level\x18\x05 \x01(\x05H\x04R\x05level\x88\x01\x01\x12#\n" +
	"\rshare_percent\x18\x06 \x01(\x02R\fsharePercentB\x05\n" +
	"\x03_idB\v\n" +
	"\t_usernameB\v\n" +
	"\t_nicknameB\f\n" +
	"\n" +
	"_parent_idB\b\n" +
	"\x06_level\"d\n" +
	"\tAuthReply\x12\x19\n" +
	"\x05token\x18\x01 \x01(\tH\x00R\x05token\x88\x01\x01\x122\n" +
	"\x04user\x18\x02 \x01(\v2\x1e.api.authn.service.v1.UserInfoR\x04userB\b\n" +
	"\x06_token\"\x80\x01\n" +
	"\fLoginRequest\x12*\n" +
	"\busername\x18\x01 \x01(\tB\t\xfaB\x06r\x04\x10\x03\x18\x14H\x00R\busername\x88\x01\x01\x12*\n" +
	"\bpassword\x18\x02 \x01(\tB\t\xfaB\x06r\x04\x10\b\x18\x14H\x01R\bpassword\x88\x01\x01B\v\n" +
	"\t_usernameB\v\n" +
	"\t_password\"4\n" +
	"\rVerifyRequest\x12\x19\n" +
	"\x05token\x18\x01 \x01(\tH\x00R\x05token\x88\x01\x01B\b\n" +
	"\x06_token\"A\n" +
	"\vVerifyReply\x122\n" +
	"\x04user\x18\x01 \x01(\v2\x1e.api.authn.service.v1.UserInfoR\x04user\"\xbd\x02\n" +
	"\x0fRegisterRequest\x12*\n" +
	"\busername\x18\x01 \x01(\tB\t\xfaB\x06r\x04\x10\x03\x18\x14H\x00R\busername\x88\x01\x01\x12*\n" +
	"\bpassword\x18\x02 \x01(\tB\t\xfaB\x06r\x04\x10\b\x18\x14H\x01R\bpassword\x88\x01\x01\x12(\n" +
	"\bnickname\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x18\x14H\x02R\bnickname\x88\x01\x01\x12 \n" +
	"\tparent_id\x18\x04 \x01(\tH\x03R\bparentId\x88\x01\x01\x12\"\n" +
	"\x05level\x18\x05 \x01(\x05B\a\xfaB\x04\x1a\x02\x18\x02H\x04R\x05level\x88\x01\x01\x12#\n" +
	"\rshare_percent\x18\x06 \x01(\x02R\fsharePercentB\v\n" +
	"\t_usernameB\v\n" +
	"\t_passwordB\v\n" +
	"\t_nicknameB\f\n" +
	"\n" +
	"_parent_idB\b\n" +
	"\x06_level2\xd0\x02\n" +
	"\x05Authn\x12g\n" +
	"\x05Login\x12\".api.authn.service.v1.LoginRequest\x1a\x1f.api.authn.service.v1.AuthReply\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/auth/login\x12p\n" +
	"\bRegister\x12%.api.authn.service.v1.RegisterRequest\x1a\x1f.api.authn.service.v1.AuthReply\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/auth/register\x12l\n" +
	"\x06Verify\x12#.api.authn.service.v1.VerifyRequest\x1a!.api.authn.service.v1.VerifyReply\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/auth/verifyB8\n" +
	"\x14api.authn.service.v1P\x01Z\x1eagents/api/authn/service/v1;v1b\x06proto3"

var (
	file_api_authn_service_v1_authn_proto_rawDescOnce sync.Once
	file_api_authn_service_v1_authn_proto_rawDescData []byte
)

func file_api_authn_service_v1_authn_proto_rawDescGZIP() []byte {
	file_api_authn_service_v1_authn_proto_rawDescOnce.Do(func() {
		file_api_authn_service_v1_authn_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_authn_service_v1_authn_proto_rawDesc), len(file_api_authn_service_v1_authn_proto_rawDesc)))
	})
	return file_api_authn_service_v1_authn_proto_rawDescData
}

var file_api_authn_service_v1_authn_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_authn_service_v1_authn_proto_goTypes = []any{
	(*UserInfo)(nil),        // 0: api.authn.service.v1.UserInfo
	(*AuthReply)(nil),       // 1: api.authn.service.v1.AuthReply
	(*LoginRequest)(nil),    // 2: api.authn.service.v1.LoginRequest
	(*VerifyRequest)(nil),   // 3: api.authn.service.v1.VerifyRequest
	(*VerifyReply)(nil),     // 4: api.authn.service.v1.VerifyReply
	(*RegisterRequest)(nil), // 5: api.authn.service.v1.RegisterRequest
}
var file_api_authn_service_v1_authn_proto_depIdxs = []int32{
	0, // 0: api.authn.service.v1.AuthReply.user:type_name -> api.authn.service.v1.UserInfo
	0, // 1: api.authn.service.v1.VerifyReply.user:type_name -> api.authn.service.v1.UserInfo
	2, // 2: api.authn.service.v1.Authn.Login:input_type -> api.authn.service.v1.LoginRequest
	5, // 3: api.authn.service.v1.Authn.Register:input_type -> api.authn.service.v1.RegisterRequest
	3, // 4: api.authn.service.v1.Authn.Verify:input_type -> api.authn.service.v1.VerifyRequest
	1, // 5: api.authn.service.v1.Authn.Login:output_type -> api.authn.service.v1.AuthReply
	1, // 6: api.authn.service.v1.Authn.Register:output_type -> api.authn.service.v1.AuthReply
	4, // 7: api.authn.service.v1.Authn.Verify:output_type -> api.authn.service.v1.VerifyReply
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_authn_service_v1_authn_proto_init() }
func file_api_authn_service_v1_authn_proto_init() {
	if File_api_authn_service_v1_authn_proto != nil {
		return
	}
	file_api_authn_service_v1_authn_proto_msgTypes[0].OneofWrappers = []any{}
	file_api_authn_service_v1_authn_proto_msgTypes[1].OneofWrappers = []any{}
	file_api_authn_service_v1_authn_proto_msgTypes[2].OneofWrappers = []any{}
	file_api_authn_service_v1_authn_proto_msgTypes[3].OneofWrappers = []any{}
	file_api_authn_service_v1_authn_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_authn_service_v1_authn_proto_rawDesc), len(file_api_authn_service_v1_authn_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_authn_service_v1_authn_proto_goTypes,
		DependencyIndexes: file_api_authn_service_v1_authn_proto_depIdxs,
		MessageInfos:      file_api_authn_service_v1_authn_proto_msgTypes,
	}.Build()
	File_api_authn_service_v1_authn_proto = out.File
	file_api_authn_service_v1_authn_proto_goTypes = nil
	file_api_authn_service_v1_authn_proto_depIdxs = nil
}
