// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"agents/app/stats/service/internal/biz"
	"agents/app/stats/service/internal/conf"
	"agents/app/stats/service/internal/data"
	"agents/app/stats/service/internal/server"
	"agents/app/stats/service/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger, registry *conf.Registry) (*kratos.App, func(), error) {
	discovery := data.NewDiscovery(logger, registry)
	dataData, cleanup, err := data.NewData(confData, logger, discovery)
	if err != nil {
		return nil, nil, err
	}
	statsRepo := data.NewStatsRepo(dataData)
	domainRepo := data.NewDomainRepo(dataData)
	commissionRepo := data.NewCommissionRepo(dataData)
	statsUseCase := biz.NewStatsUseCase(statsRepo, logger, domainRepo, commissionRepo)
	statsService := service.NewStatsService(statsUseCase)
	grpcServer := server.NewGRPCServer(confServer, logger, statsService)
	httpServer := server.NewHTTPServer(confServer, logger, statsService)
	registrar := server.NewRegistrar(logger, registry)
	app := newApp(logger, grpcServer, httpServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
